### PR TITLE
Feature#42 list company branches page styling

### LINKED ISSUE #42: List company branches page styling
# REQUIREMENTS
- Add a table to list all registered company branches.
- Add to that table simple styling using bootstrap.

### PR DESCRIPTION
**Pull request by lucasvidela94**
# Description
-Create table for branches and table styling for the same component.
 
  ## Screenshots
image

### CODE REVIEW

**Review by d1eg0dev — APPROVED** [review]
Cool!

**Review by ever864 — APPROVED** [review]
LGTM!

**Review by HikingCarrot7 — APPROVED** [review]
LGTM'nt!

**Review by Jumaquba — APPROVED** [review]
Good job!

**Pull request merged**
