### PR TITLE
Fix relationship between users and attendances & check out logic

### LINKED ISSUE #51: Create check out logic
# REQUIREMENTS
Create check out logic

### PR DESCRIPTION
**Pull request by HikingCarrot7**
Co-authored-by: lucasvidela94 <lucas.videla994@gmail.com>
Co-authored-by: guillermo-delprado <galfonso.delprado@gmail.com>
Co-authored-by: HikingCarrot7 <ricardoibarra2044@gmail.com>

# Description
- Fixed relationship between employeyes & attendaces.
- Implemented check out logic.
- Fixed some nasty bugs.

### CODE REVIEW

**Review by EdwardMD — DISMISSED** [review]
LGTM!

**Review by lucasvidela94 — DISMISSED** [review]

**Review by guillermo-delprado — DISMISSED** [review]
GOOD

**Review by lucasvidela94 — APPROVED** [review]

**Review by guillermo-delprado — APPROVED** [review]
LG

**Review by AgustinPalmaM — APPROVED** [review]
LGTM

**Pull request merged**
