### PR TITLE
Feature#44 single employee page styling

### LINKED ISSUE #44: Single employee page styling
# REQUIREMENTS
- Add simple styling to single employee page using bootstrap

### PR DESCRIPTION
**Pull request by lucasvidela94**
# Description
Modified view for employee description in show functionality.

### CODE REVIEW

**Review by acorzo — DISMISSED** [review]
Good job 👍.

**Review by acorzo — APPROVED** [review]
LGTM 👍

**Review by YilKanda — APPROVED** [review]
Good!

**Review by ever864 — APPROVED** [review]
LGTM!

**Pull request merged**
