### PR TITLE
Feature#57 hot fixes

### LINKED ISSUE #57: Hot fixes
# REQUIREMENTS
- Fix admin login page styling.
- Fix employees & branches tables styling

### PR DESCRIPTION
**Pull request by lucasvidela94**
# Description
Fix admin login page styling.
Fix employees & branches tables styling

### CODE REVIEW

**Review by EdwardMD — APPROVED** [review]
LGTM!

**Review by EdwardMD — APPROVED** [review]
LGTM!

**Review by AgustinPalmaM — APPROVED** [review]
LGTM

**Review by ever864 — APPROVED** [review]
lgtm!

**Review by d1eg0dev — APPROVED** [review]
LGTM!

**Review by acorzo — APPROVED** [review]
LGTM 👍

**Pull request merged**
