### PR TITLE
Feature#69 average check in check out by month

### LINKED ISSUE #69: Average check in & check out by month
# REQUIREMENTS
Add logic to calculate average check in & check out by month

### PR DESCRIPTION
**Pull request by lucasvidela94**
# Description
Added new feature that allows to calculate the average assistence per month.

### CODE REVIEW

**Review by EdwardMD — APPROVED** [review]
LGTM!

**Review by EdwardMD — DISMISSED** [review]
LGTM!

**Review by ever864 — APPROVED** [review]
LGTM!

**Review by HikingCarrot7 — APPROVED** [review]
LGTM!

**Review by MatiasDevJam — APPROVED** [review]
LGTM! nice work!

**Pull request merged**
