### PR TITLE
Added proposal ERD diagram

### LINKED ISSUE #23: Entity relationship diagram
# REQUIREMENTS
Create the ERD for the database

### PR DESCRIPTION
**Pull request by HikingCarrot7**
Co-authored-by: lucasvidela94 <lucas.videla994@gmail.com>
Co-authored-by: guillermo-delprado <galfonso.delprado@gmail.com>
Co-authored-by: HikingCarrot7 <ricardoibarra2044@gmail.com>

# Description
Added first ERD version

# Diagram
erd

### CODE REVIEW

**Review by ever864 — APPROVED** [review]
LGTM!

**Review by carlos-ssh — APPROVED** [review]
# 🍾🍾 **STATUS APPROVED** 👏🏽👏🏽

Hi team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Approved


Cheers and Happy coding!👏👏👏

**Review by EdwardMD — APPROVED** [review]
looks great

**Review by acorzo — APPROVED** [review]
Correct, review check_in and check_out field is of type date or it should be datetime.

**Pull request merged**
