### PR TITLE
Feature#59 fix dashboard clock functionality

### LINKED ISSUE #59: Fix dashboard clock functionality
# REQUIREMENTS
Fix dashboard clock functionality and add button to redirect admin panel.

### PR DESCRIPTION
**Pull request by lucasvidela94**
# Description
Added new buttons to admin panel and fix clock functionality.

image

### CODE REVIEW

**Review by HikingCarrot7 — APPROVED** [review]
LGMT!

**Review by HikingCarrot7 — APPROVED** [review]
LGMT!

**Review by HikingCarrot7 — APPROVED** [review]
LGMT!

**Review by AgustinPalmaM — APPROVED** [review]
LGTM

**Review by ever864 — APPROVED** [review]
LGTM!

**Pull request merged**
