### PR TITLE
Feature#27 configurate admin panel

### LINKED ISSUE #27: Configurate admin panel
# REQUIREMENTS
Configurate admin panel

### PR DESCRIPTION
**Pull request by HikingCarrot7**
# Description
Added the functionality so that only employees with admin role can access the admin panel

### CODE REVIEW

**Review by carlos-ssh — APPROVED** [review]
# 🍾🍾 **STATUS APPROVED** 👏🏽👏🏽

Hi team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Approved


Cheers and Happy coding!👏👏👏

**Review by ever864 — APPROVED** [review]
LGTM!

**Review by BillowyBead34 — APPROVED** [review]
LGTM!

**Review by EdwardMD — APPROVED** [review]
good job!

**Review by V-Juarez — APPROVED** [review]

**Pull request merged**
