### PR TITLE
Added pagination for branches & employees pages

### LINKED ISSUE #62: Add pagination for branches & employees pages
# REQUIREMENTS
- Add simple pagination to branches & employees pages

### PR DESCRIPTION
**Pull request by lucasvidela94**
Co-authored-by: lucasvidela94 <lucas.videla994@gmail.com>
Co-authored-by: guillermo-delprado <galfonso.delprado@gmail.com>
Co-authored-by: HikingCarrot7 <ricardoibarra2044@gmail.com>

# Description
Added Pagy gem to gem file.
Refactor Sign out button.

### CODE REVIEW

**Review by acorzo — DISMISSED** [review]
Good job 👍

**Review by V-Juarez — DISMISSED** [review]

**Review by AgustinPalmaM — APPROVED** [review]
LGTM

**Review by acorzo — APPROVED** [review]
Good Job 👍

**Review by HikingCarrot7 — APPROVED** [review]
LGMT!

**Pull request merged**
